<script setup>
import { onMounted, ref } from 'vue'
import { api } from '../../api'
import LoadState from '../../components/LoadState.vue'
const data = ref(null), loading = ref(true), error = ref('')
async function load() { loading.value = true; error.value = ''; try { data.value = await api.get('/admin/dashboard') } catch (e) { error.value = e.message } finally { loading.value = false } }
onMounted(load)
</script>
<template><div class="page-heading"><div><div class="eyebrow">OPERATIONS OVERVIEW</div><h1>运营概览</h1><p>交易进展与兑换码库存，一目了然。</p></div><el-button @click="load">刷新数据 ↻</el-button></div><LoadState :loading="loading" :error="error" @retry="load"><template v-if="data"><div class="metric-grid"><div class="metric-card"><span>商品总数</span><strong>{{ data.productCount }}</strong><small>所有商品</small></div><div class="metric-card"><span>今日订单</span><strong>{{ data.todayOrders }}</strong><small>按订单创建时间统计</small></div><div class="metric-card accent"><span>可用兑换码</span><strong>{{ data.availableCodes }}</strong><small>未分配且未过期</small></div><div class="metric-card"><span>已发货订单</span><strong>{{ data.deliveredOrders }}</strong><small>已交付与已完成</small></div></div><div class="dashboard-grid"><section class="surface"><div class="panel-title"><div><h2>低库存提醒</h2><p class="muted">及时补充兑换码，保证交付体验。</p></div><RouterLink to="/admin/codes" class="text-link">补充库存 →</RouterLink></div><el-empty v-if="!data.lowStockProducts?.length" description="暂无低库存商品" :image-size="80" /><el-table v-else :data="data.lowStockProducts"><el-table-column prop="name" label="商品" min-width="160" /><el-table-column prop="stock" label="可用库存" width="110"><template #default="{ row }"><el-tag :type="row.stock === 0 ? 'danger' : 'warning'">{{ row.stock }} 条</el-tag></template></el-table-column><el-table-column label="操作" width="100"><template #default="{ row }"><RouterLink :to="{ path: '/admin/codes', query: { productId: row.id } }" class="text-link">导入卡密</RouterLink></template></el-table-column></el-table></section><section class="surface quick-actions"><div class="eyebrow">QUICK ACTIONS</div><h2>常用操作</h2><RouterLink to="/admin/products"><span>◈</span><div><strong>维护商品</strong><p>新增、编辑与上下架</p></div><b>↗</b></RouterLink><RouterLink to="/admin/codes"><span>⌘</span><div><strong>导入兑换码</strong><p>批量补充商品库存</p></div><b>↗</b></RouterLink><RouterLink to="/admin/orders"><span>▤</span><div><strong>查询订单</strong><p>核对交易与发货状态</p></div><b>↗</b></RouterLink></section></div></template></LoadState></template>
