<script setup>
import { onMounted, reactive, ref } from 'vue'
import { api, time } from '../../api'
import { session } from '../../auth'
import { usePage } from '../../composables/usePage'
import { ElMessage, ElMessageBox } from 'element-plus'
import LoadState from '../../components/LoadState.vue'
const filters = reactive({ keyword: '' }), { rows, total, page, loading, error, load, search } = usePage('/admin/users', filters), updating = ref(null)
async function toggle(row) { const status = row.status === 1 ? 0 : 1; try { await ElMessageBox.confirm(`确认${status ? '启用' : '禁用'}用户「${row.username}」？此操作会记录审计日志。`, '变更账号状态', { confirmButtonText: '确认', cancelButtonText: '取消', type: 'warning' }); updating.value = row.id; await api.put(`/admin/users/${row.id}/status`, { status }); ElMessage.success('账号状态已更新'); await load() } catch (e) { if (e instanceof Error) ElMessage.error(e.message) } finally { updating.value = null } }
onMounted(load)
</script>
<template><div class="page-heading"><div><div class="eyebrow">ACCOUNT MANAGEMENT</div><h1>用户管理</h1><p>查看用户基础资料，维护账号使用状态。</p></div></div><section class="surface admin-table-panel"><form class="table-toolbar" @submit.prevent="search"><el-input v-model="filters.keyword" placeholder="搜索用户名" clearable aria-label="搜索用户名" @clear="search" /><el-button native-type="submit">查询</el-button><span class="toolbar-count">共 {{ total }} 位</span></form><LoadState :loading="loading" :error="error" :empty="!rows.length" empty-text="没有符合条件的用户" @retry="load"><el-table :data="rows"><el-table-column prop="id" label="用户 ID" width="100" /><el-table-column prop="username" label="用户名" min-width="180" /><el-table-column label="角色" width="130"><template #default="{ row }"><el-tag :type="row.role === 'ADMIN' ? 'primary' : 'info'">{{ row.role === 'ADMIN' ? '管理员' : '普通用户' }}</el-tag></template></el-table-column><el-table-column label="状态" width="110"><template #default="{ row }"><el-tag :type="row.status === 1 ? 'success' : 'danger'">{{ row.status === 1 ? '正常' : '已禁用' }}</el-tag></template></el-table-column><el-table-column label="注册时间" min-width="190"><template #default="{ row }">{{ time(row.createdAt) }}</template></el-table-column><el-table-column label="操作" width="130" fixed="right"><template #default="{ row }"><span v-if="row.role === 'ADMIN'" class="muted">{{ row.id === session.user?.id ? '当前账号' : '管理员受保护' }}</span><el-button v-else link :type="row.status === 1 ? 'danger' : 'success'" :loading="updating === row.id" @click="toggle(row)">{{ row.status === 1 ? '禁用' : '启用' }}</el-button></template></el-table-column></el-table><el-pagination v-if="total > 15" v-model:current-page="page" :page-size="15" :total="total" layout="total, prev, pager, next" class="pagination" @current-change="load" /></LoadState></section></template>
