FROM node:22-alpine AS build
WORKDIR /workspace
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:1.28-alpine
COPY --from=build /workspace/dist /usr/share/nginx/html
COPY deploy-nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80 443
