<script setup>
import { computed, watch, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { api, money, time, orderStates, codeStates, stateType } from '../api'
import { ElMessage, ElMessageBox } from 'element-plus'
import LoadState from '../components/LoadState.vue'
import { setRedeemDraft } from '../redeemDraft'
const route = useRoute(), router = useRouter(), order = ref(null), loading = ref(true), error = ref(''), busy = ref(false)
const delivered = computed(() => ['DELIVERED', 'COMPLETED'].includes(order.value?.status))
async function load() { loading.value = true; error.value = ''; try { order.value = await api.get(`/orders/${route.params.orderNo}`) } catch (e) { error.value = e.message } finally { loading.value = false } }
async function copy() { try { await navigator.clipboard.writeText(order.value.redeemCode.code); ElMessage.success('兑换码已复制') } catch { ElMessage.warning('自动复制不可用，请选中兑换码手动复制。') } }
function goRedeem() { setRedeemDraft(order.value.redeemCode.code); router.push('/redeem') }
async function cancel() { try { await ElMessageBox.confirm('确定取消这笔待支付订单？', '取消订单', { confirmButtonText: '确认取消', cancelButtonText: '返回', type: 'warning' }); busy.value = true; order.value = await api.post(`/orders/${order.value.orderNo}/cancel`) } catch (e) { if (e instanceof Error) ElMessage.error(e.message) } finally { busy.value = false } }
watch(() => route.params.orderNo, load, { immediate: true })
</script>
<template><div class="content-container"><RouterLink to="/orders" class="back-link">← 返回我的订单</RouterLink><LoadState :loading="loading" :error="error" @retry="load"><template v-if="order"><div v-if="route.meta.success && delivered" class="success-banner"><div class="success-mark">✓</div><div><div class="eyebrow">DELIVERY COMPLETE</div><h1>模拟支付成功，已自动发货。</h1><p>你的兑换码已就绪，在下方查看并前往自助兑换。</p></div></div><div v-else class="page-heading"><div><div class="eyebrow">ORDER DETAILS</div><h1>订单详情</h1><p class="mono">{{ order.orderNo }}</p></div><el-tag :type="stateType(order.status)" size="large">{{ orderStates[order.status] || order.status }}</el-tag></div><div class="order-detail-grid"><section class="surface"><div class="panel-title"><h2>订单信息</h2><el-tag :type="stateType(order.status)">{{ orderStates[order.status] || order.status }}</el-tag></div><div class="order-snapshot"><span class="order-product-icon">◈</span><div><h3>{{ order.productName }}</h3><p>数字商品 · 数量 1 · 模拟支付</p></div><strong>¥ {{ money(order.amount) }}</strong></div><dl class="detail-list"><div><dt>订单号</dt><dd class="mono">{{ order.orderNo }}</dd></div><div><dt>下单单价</dt><dd>¥ {{ money(order.unitPrice ?? order.amount) }}</dd></div><div><dt>创建时间</dt><dd>{{ time(order.createdAt) }}</dd></div><div v-if="order.status === 'WAIT_PAY'"><dt>支付截止</dt><dd>{{ time(order.expireAt) }}</dd></div><div><dt>支付时间</dt><dd>{{ time(order.paidAt) }}</dd></div><div><dt>发货时间</dt><dd>{{ time(order.deliveredAt) }}</dd></div></dl><div v-if="order.status === 'WAIT_PAY'" class="action-row"><RouterLink :to="`/checkout/${order.orderNo}`" class="solid-link">继续模拟支付 →</RouterLink><el-button :loading="busy" @click="cancel">取消订单</el-button></div></section><section class="surface code-panel"><div class="eyebrow">YOUR REDEEM CODE</div><h2>专属兑换码</h2><template v-if="delivered && order.redeemCode"><el-tag :type="stateType(order.redeemCode.status)">{{ codeStates[order.redeemCode.status] || order.redeemCode.status }}</el-tag><div class="revealed-code">{{ order.redeemCode.code }}</div><el-button class="full-width" @click="copy">复制兑换码</el-button><el-button v-if="order.redeemCode.status === 'ASSIGNED'" type="primary" class="full-width redeem-button" @click="goRedeem">前往自助兑换 →</el-button><dl class="detail-list compact"><div><dt>有效期至</dt><dd>{{ order.redeemCode.expiredAt ? time(order.redeemCode.expiredAt) : '长期有效' }}</dd></div><div v-if="order.redeemCode.usedAt"><dt>兑换时间</dt><dd>{{ time(order.redeemCode.usedAt) }}</dd></div></dl><p class="muted">兑换码与当前账号绑定，请妥善保存。</p></template><div v-else class="code-awaiting"><span>◈</span><p>{{ order.status === 'WAIT_PAY' ? '完成模拟支付后，兑换码将自动显示在这里。' : order.status === 'PAID' ? '系统正在发货，请稍后刷新。' : '该订单没有可用兑换码。' }}</p><el-button @click="load">刷新订单</el-button></div></section></div></template></LoadState></div></template>
