<script setup>
import { onMounted, ref } from 'vue'
import { api, money, time, orderStates, stateType } from '../api'
import LoadState from '../components/LoadState.vue'
const rows = ref([]), total = ref(0), page = ref(1), status = ref(''), loading = ref(true), error = ref('')
async function load() { loading.value = true; error.value = ''; try { const data = await api.get('/orders', { params: { page: page.value, size: 10, status: status.value || undefined } }); rows.value = data.records; total.value = data.total } catch (e) { error.value = e.message } finally { loading.value = false } }
function filter() { page.value = 1; load() }
onMounted(load)
</script>
<template><div class="content-container"><div class="page-heading"><div><div class="eyebrow">YOUR PURCHASES</div><h1>我的订单</h1><p>查看交易进度，获取属于你的兑换码。</p></div><RouterLink to="/" class="outline-link">继续选购 ↗</RouterLink></div><div class="filter-tabs"><button :class="{ active: !status }" @click="status = ''; filter()">全部订单</button><button v-for="(label, state) in orderStates" :key="state" :class="{ active: status === state }" @click="status = state; filter()">{{ label }}</button></div><LoadState :loading="loading" :error="error" :empty="!rows.length" empty-text="还没有符合条件的订单" @retry="load"><template #empty><RouterLink to="/" class="solid-link">去看看商品 →</RouterLink></template><div class="order-list"><article v-for="order in rows" :key="order.orderNo" class="order-list-card"><div class="order-list-top"><span class="mono">{{ order.orderNo }}</span><el-tag :type="stateType(order.status)">{{ orderStates[order.status] || order.status }}</el-tag></div><div class="order-list-content"><div class="order-product-icon">◈</div><div class="order-list-product"><h3>{{ order.productName }}</h3><p>{{ time(order.createdAt) }} · 数量 1</p></div><strong class="order-list-price">¥ {{ money(order.amount) }}</strong><div class="order-list-actions"><RouterLink v-if="order.status === 'WAIT_PAY'" :to="`/checkout/${order.orderNo}`" class="solid-link small">去支付</RouterLink><RouterLink :to="`/orders/${order.orderNo}`" class="outline-link small">订单详情 →</RouterLink></div></div></article></div><el-pagination v-if="total > 10" v-model:current-page="page" :total="total" :page-size="10" layout="prev, pager, next" class="pagination" @current-change="load" /></LoadState></div></template>
