<script setup>
import { reactive, ref } from 'vue'
import { session, clearSession } from '../auth'
import { api, time } from '../api'
import { ElMessage } from 'element-plus'
import { useRouter } from 'vue-router'
const router = useRouter(), form = reactive({ currentPassword: '', newPassword: '', confirm: '' }), busy = ref(false), error = ref('')
async function change() { error.value = ''; if (!form.currentPassword || form.newPassword.length < 8 || new TextEncoder().encode(form.newPassword).length > 72) { error.value = '请输入当前密码；新密码至少 8 个字符且 UTF-8 编码长度不超过 72 字节。'; return }; if (form.newPassword !== form.confirm) { error.value = '两次输入的新密码不一致。'; return }; busy.value = true; try { await api.put('/auth/password', { currentPassword: form.currentPassword, newPassword: form.newPassword }); clearSession(); ElMessage.success('密码已修改，请重新登录。'); router.replace('/login') } catch (e) { error.value = e.message } finally { busy.value = false } }
</script>
<template><div class="content-container"><div class="page-heading"><div><div class="eyebrow">YOUR ACCOUNT</div><h1>个人中心</h1><p>管理账号资料与登录密码。</p></div></div><div class="profile-grid"><section class="surface"><div class="profile-identity"><span class="avatar large">{{ session.user?.username?.[0]?.toUpperCase() }}</span><div><h2>{{ session.user?.username }}</h2><el-tag>{{ session.user?.role === 'ADMIN' ? '管理员' : '普通用户' }}</el-tag></div></div><dl class="detail-list"><div><dt>账号 ID</dt><dd>{{ session.user?.id }}</dd></div><div v-if="session.user?.createdAt"><dt>注册时间</dt><dd>{{ time(session.user.createdAt) }}</dd></div></dl><RouterLink to="/orders" class="outline-link full-width centered">我的订单 →</RouterLink><RouterLink to="/redeem" class="outline-link full-width centered redeem-button">兑换中心 →</RouterLink></section><section class="surface"><h2>修改密码</h2><p class="muted">修改后需要重新登录。</p><el-alert v-if="error" :title="error" type="error" :closable="false" show-icon class="form-alert" /><form @submit.prevent="change"><label for="current-password" class="field-label">当前密码</label><el-input id="current-password" v-model="form.currentPassword" type="password" show-password autocomplete="current-password" :maxlength="72" /><label for="new-password" class="field-label">新密码</label><el-input id="new-password" v-model="form.newPassword" type="password" show-password autocomplete="new-password" :maxlength="72" placeholder="至少 8 个字符" /><label for="confirm-password" class="field-label">确认新密码</label><el-input id="confirm-password" v-model="form.confirm" type="password" show-password autocomplete="new-password" :maxlength="72" /><el-button type="primary" native-type="submit" :loading="busy" class="auth-submit">保存新密码</el-button></form></section></div></div></template>
