<script setup>
import { onMounted, ref } from 'vue'
import { api, time } from '../api'
import { ElMessage } from 'element-plus'
import LoadState from '../components/LoadState.vue'
import { takeRedeemDraft } from '../redeemDraft'
const code = ref(takeRedeemDraft()), busy = ref(false), error = ref(''), result = ref(null), records = ref([]), loading = ref(true), recordError = ref(''), page = ref(1), total = ref(0)
async function load() { loading.value = true; recordError.value = ''; try { const data = await api.get('/redeem/records', { params: { page: page.value, size: 10 } }); records.value = data.records; total.value = data.total } catch (e) { recordError.value = e.message } finally { loading.value = false } }
async function redeem() { error.value = ''; result.value = null; if (!code.value.trim()) { error.value = '请输入兑换码。'; return }; busy.value = true; try { result.value = await api.post('/redeem', { code: code.value.trim() }); code.value = ''; ElMessage.success('兑换成功'); await load() } catch (e) { error.value = e.message; await load() } finally { busy.value = false } }
onMounted(load)
</script>
<template><div class="content-container"><div class="page-heading"><div><div class="eyebrow">SELF-SERVICE REDEMPTION</div><h1>兑换中心</h1><p>输入你已购买的兑换码，完成自助兑换。</p></div><RouterLink to="/orders" class="outline-link">查看我的兑换码 →</RouterLink></div><div class="redeem-layout"><section class="surface redeem-form"><div class="redeem-glyph">◈</div><h2>兑换你的数字商品</h2><p class="muted">兑换码与购买账号绑定，且仅能使用一次。</p><el-alert v-if="error" :title="error" type="error" :closable="false" show-icon class="form-alert" /><form @submit.prevent="redeem"><label class="field-label" for="redeem-code">兑换码</label><el-input id="redeem-code" v-model="code" :maxlength="128" placeholder="请输入或粘贴完整兑换码" size="large" class="mono-input" autocomplete="off" /><el-button type="primary" native-type="submit" size="large" class="full-width auth-submit" :loading="busy">确认兑换 →</el-button></form><div v-if="result" class="redeem-result" role="status"><strong>✓ {{ result.message || '兑换成功' }}</strong><p>{{ result.productName }}</p><RouterLink :to="`/orders/${result.orderNo}`">查看订单 →</RouterLink></div><div class="info-note"><strong>找不到兑换码？</strong><p>进入「我的订单」，打开已发货订单，即可查看与复制兑换码。</p></div></section><section class="surface redeem-records"><div class="panel-title"><h2>兑换记录</h2><span class="muted">{{ total }} 条</span></div><LoadState :loading="loading" :error="recordError" :empty="!records.length" empty-text="还没有兑换记录" @retry="load"><div v-for="record in records" :key="record.id" class="record-row"><div><h3>{{ record.productName || record.orderNo || '兑换记录' }}</h3><p>{{ time(record.createdAt || record.usedAt) }}</p><p v-if="record.reason" class="muted">{{ record.reason }}</p></div><el-tag :type="record.result === 'FAILED' ? 'danger' : 'success'">{{ record.result === 'FAILED' ? '兑换失败' : '兑换成功' }}</el-tag></div><el-pagination v-if="total > 10" v-model:current-page="page" :total="total" :page-size="10" layout="prev, pager, next" class="pagination" @current-change="load" /></LoadState></section></div></div></template>
