<script setup>
import { onMounted, ref } from 'vue'
import { api, money } from '../api'
import LoadState from '../components/LoadState.vue'
import ProductArt from '../components/ProductArt.vue'
const products = ref([]), total = ref(0), page = ref(1), keyword = ref(''), loading = ref(true), error = ref('')
let latest = 0
async function load() { const request = ++latest; loading.value = true; error.value = ''; try { const data = await api.get('/products', { params: { page: page.value, size: 8, keyword: keyword.value.trim() || undefined } }); if (request === latest) { products.value = data.records; total.value = data.total } } catch (e) { if (request === latest) error.value = e.message } finally { if (request === latest) loading.value = false } }
function search() { page.value = 1; load() }
onMounted(load)
</script>
<template>
  <section class="store-hero"><div class="hero-copy"><div class="eyebrow"><span class="status-dot"></span>数字商品自助交付平台</div><h1>所需好物，<br>即刻<span>交付。</span></h1><p>发现数字商品，体验从下单到兑换的完整流程。<br class="desktop-only">模拟支付成功后，兑换码自动送达你的订单。</p><div class="hero-actions"><a href="#products" class="solid-link">浏览商品 <span>↗</span></a><RouterLink to="/redeem" class="text-link">已有兑换码？去兑换 →</RouterLink></div><div class="hero-points"><span><i>✓</i> 自动分配兑换码</span><span><i>✓</i> 全程可追踪</span><span><i>✓</i> 仅模拟支付</span></div></div><div class="hero-visual" aria-hidden="true"><div class="visual-orbit orbit-one"></div><div class="visual-orbit orbit-two"></div><span class="visual-label">DELIVERY SYSTEM / ONLINE</span><div class="delivery-card"><div class="delivery-card-top"><span class="tiny-dot"></span> DIGITAL DELIVERY <span>↗</span></div><div class="delivery-glyph">↗</div><div class="delivery-card-bottom"><strong>即刻送达</strong><span>AUTOMATED<br>SELF-SERVICE</span></div></div><div class="floating-note"><span class="note-icon">✓</span><span>模拟支付完成后<br><strong>自动发货 · 自助兑换</strong></span></div><span class="visual-bottom">01 — BROWSE / 02 — PAY / 03 — REDEEM</span></div></section>
  <section id="products" class="catalog"><div class="section-heading"><div><div class="eyebrow">THE DIGITAL COLLECTION</div><h2>精选数字商品<span v-if="!loading && !error" class="count-badge">{{ total }}</span></h2></div><form class="search-form" @submit.prevent="search"><el-input v-model="keyword" placeholder="搜索商品名称" clearable aria-label="搜索商品名称" @clear="search"><template #prefix>⌕</template></el-input><el-button native-type="submit">搜索</el-button></form></div><LoadState :loading="loading" :error="error" :empty="!products.length" empty-text="没有找到商品，请尝试其他关键词" @retry="load"><div class="product-grid"><RouterLink v-for="(product, index) in products" :key="product.id" :to="`/product/${product.id}`" class="product-card"><ProductArt :product="product" :index="index" /><div class="product-card-body"><span class="stock-pill" :class="{ sold: product.stock === 0 }"><span></span>{{ product.stockLabel || (product.stock > 0 ? '有货' : '暂时缺货') }}</span><h3>{{ product.name }}</h3><p>{{ product.subtitle || '数字商品 · 模拟交易 · 自动交付' }}</p><div class="product-card-bottom"><div class="price"><small>¥</small>{{ money(product.price) }}</div><span class="card-arrow">↗</span></div></div></RouterLink></div><el-pagination v-if="total > 8" v-model:current-page="page" :total="total" :page-size="8" layout="prev, pager, next" class="pagination" @current-change="load" /></LoadState></section>
  <section class="how-it-works"><div><span class="eyebrow">HOW IT WORKS</span><h2>三步，完成自助交付。</h2><p>流程清晰，每一步都能在订单中查看。</p></div><ol class="steps-list"><li><span>01</span><div><h3>选择商品</h3><p>查看详情与库存，登录后创建订单。</p></div></li><li><span>02</span><div><h3>模拟支付</h3><p>在测试收银台完成支付，系统自动发货。</p></div></li><li><span>03</span><div><h3>自助兑换</h3><p>在订单中获取兑换码，前往兑换中心使用。</p></div></li></ol></section>
</template>
